################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  dashboard: true
################################################################
# Docker configuration provider
################################################################
providers:
  docker: 
    watch: true
    exposedByDefault: false
################################################################
# Traefik Logging
################################################################
log:
  level: INFO
################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"