---
version: '3'
services:
#########################################################
## TRAEFIK
#########################################################
  reverse-proxy: 
    container_name: traefik
    image: traefik:v2.6.3
    ports:
      - 80:80
      - 8080:8080 #Management UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
#########################################################
## WEBSERVERS
#########################################################
  whoami:
    image: traefik/whoami
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"