---
version: '3'
services:
#########################################################
## TRAEFIK
#########################################################
  reverse-proxy: 
    container_name: traefik
    image: traefik:v2.6.3
    networks:
      - traefik
    ports:
      - 80:80
      - 8080:8080 #Management UI
    command:
     - --api.dashboard=true
     - --providers.docker=true
     - --log.level=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
#########################################################
## WEBSERVERS
#########################################################
#  whoami:
#    image: traefik/whoami
#    labels: 
#      - "traefik.enable=true"
#      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"